// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.EntityFramework.Connections;

#nullable disable

namespace WebApi.EntityFramework.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20241124051453_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Models.Entities.Hunter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Hunter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 12,
                            Name = "Gon Freecss"
                        },
                        new
                        {
                            Id = 2,
                            Age = 12,
                            Name = "Killua Zoldyck"
                        },
                        new
                        {
                            Id = 3,
                            Age = 17,
                            Name = "Kurapika Kurta"
                        },
                        new
                        {
                            Id = 4,
                            Age = 19,
                            Name = "Leorio Paladiknight"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Entities.Hunter_Nen", b =>
                {
                    b.Property<int>("Hunter_Id")
                        .HasColumnType("int");

                    b.Property<int>("Nen_Id")
                        .HasColumnType("int");

                    b.HasKey("Hunter_Id", "Nen_Id");

                    b.HasIndex("Nen_Id");

                    b.ToTable("Hunter_Nen");

                    b.HasData(
                        new
                        {
                            Hunter_Id = 1,
                            Nen_Id = 1
                        },
                        new
                        {
                            Hunter_Id = 2,
                            Nen_Id = 2
                        },
                        new
                        {
                            Hunter_Id = 3,
                            Nen_Id = 3
                        },
                        new
                        {
                            Hunter_Id = 3,
                            Nen_Id = 6
                        },
                        new
                        {
                            Hunter_Id = 4,
                            Nen_Id = 4
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Entities.Nen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Nen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Si un estudiante aumenta la cantidad de agua en el vaso durante su prueba del agua, es de Intensificación",
                            Name = "Intensificación"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Si un estudiante cambia el sabor del agua durante su prueba del agua es un Transformador",
                            Name = "Transformación"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Si un estudiante hace aparecer impurezas en el agua del vaso durante su prueba ellos son Materialización",
                            Name = "Materialización"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Si un estudiante cambia el color del agua en el vaso durante su prueba del agua, es un Emisor",
                            Name = "Emisión"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Si un estudiante mueve la hoja flotando en el agua del vaso durante su prueba del agua, es un Manipulador",
                            Name = "Manipulación"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Si un estudiante hace algún otro efecto durante su prueba del agua, son Especialistas",
                            Name = "Especialización"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Models.Entities.Hunter_Nen", b =>
                {
                    b.HasOne("ClassLibrary.Models.Entities.Hunter", "Hunter")
                        .WithMany("Hunter_Nen")
                        .HasForeignKey("Hunter_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Models.Entities.Nen", "Nen")
                        .WithMany("Hunter_Nen")
                        .HasForeignKey("Nen_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hunter");

                    b.Navigation("Nen");
                });

            modelBuilder.Entity("ClassLibrary.Models.Entities.Hunter", b =>
                {
                    b.Navigation("Hunter_Nen");
                });

            modelBuilder.Entity("ClassLibrary.Models.Entities.Nen", b =>
                {
                    b.Navigation("Hunter_Nen");
                });
#pragma warning restore 612, 618
        }
    }
}
