// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_CodeFirst.Connections;

#nullable disable

namespace WebApi_CodeFirst.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    [Migration("20240603161848_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaDeClases.Models.CazadorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Cazadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 12,
                            Nombre = "Gon Freecss"
                        },
                        new
                        {
                            Id = 2,
                            Edad = 12,
                            Nombre = "Killua Zoldyck"
                        },
                        new
                        {
                            Id = 3,
                            Edad = 17,
                            Nombre = "Kurapika Kurta"
                        },
                        new
                        {
                            Id = 4,
                            Edad = 19,
                            Nombre = "Leorio Paladiknight"
                        });
                });

            modelBuilder.Entity("BibliotecaDeClases.Models.CazadorNenModel", b =>
                {
                    b.Property<int>("Id_Cazador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Nen")
                        .HasColumnType("int");

                    b.HasKey("Id_Cazador", "Id_Nen");

                    b.HasIndex("Id_Nen");

                    b.ToTable("CazadorNen");

                    b.HasData(
                        new
                        {
                            Id_Cazador = 1,
                            Id_Nen = 1
                        },
                        new
                        {
                            Id_Cazador = 2,
                            Id_Nen = 2
                        },
                        new
                        {
                            Id_Cazador = 3,
                            Id_Nen = 3
                        },
                        new
                        {
                            Id_Cazador = 3,
                            Id_Nen = 6
                        },
                        new
                        {
                            Id_Cazador = 4,
                            Id_Nen = 4
                        });
                });

            modelBuilder.Entity("BibliotecaDeClases.Models.NenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Nen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Si un estudiante aumenta la cantidad de agua en el vaso durante su prueba del agua, es de Intensificación",
                            Nombre = "Intensificación"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Si un estudiante cambia el sabor del agua durante su prueba del agua es un Transformador",
                            Nombre = "Transformación"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Si un estudiante hace aparecer impurezas en el agua del vaso durante su prueba ellos son Materialización",
                            Nombre = "Materialización"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Si un estudiante cambia el color del agua en el vaso durante su prueba del agua, es un Emisor",
                            Nombre = "Emisión"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Si un estudiante mueve la hoja flotando en el agua del vaso durante su prueba del agua, es un Manipulador",
                            Nombre = "Manipulación"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Si un estudiante hace algún otro efecto durante su prueba del agua, son Especialistas",
                            Nombre = "Especialización"
                        });
                });

            modelBuilder.Entity("BibliotecaDeClases.Models.CazadorNenModel", b =>
                {
                    b.HasOne("BibliotecaDeClases.Models.CazadorModel", "Cazador")
                        .WithMany("Cazador_Nen")
                        .HasForeignKey("Id_Cazador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaDeClases.Models.NenModel", "Nen")
                        .WithMany("Cazador_Nen")
                        .HasForeignKey("Id_Nen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cazador");

                    b.Navigation("Nen");
                });

            modelBuilder.Entity("BibliotecaDeClases.Models.CazadorModel", b =>
                {
                    b.Navigation("Cazador_Nen");
                });

            modelBuilder.Entity("BibliotecaDeClases.Models.NenModel", b =>
                {
                    b.Navigation("Cazador_Nen");
                });
#pragma warning restore 612, 618
        }
    }
}
